export const headers = {
  Authorization: 'bearer  ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
  'Content-Type': 'application/json',
};
export const GET_ADS_PAGES = '[PALCAR] GET AD PAGGEDS';
export const SELECT_AD = '[PALCAR] SELECT AD';
export const TOGGLEPOPUP = '[PALCAR] TOGGLE LOGIN POPUP';
export const TOGGLE_AUTH = '[PALCAR] TOGGLE AUTH';
export const TOGGLE_LOADER = '[PALCAR] TOOGLE LOADER';
export const GET_SHOWROOM = '[PALCAR] GET SHOWROOM DATA';
export const SET_ACTIVE_SHOWROOM = '[PALCAR] SET ACTIVE SHOWROOM';
export const GET_FAV_DATA = '[PALCAR] GET FAVOURITE DATA';
export const SET_USER_AUTHENTICATE = '[PALCAR] SET USER AUTHENTICATE';
export const SET_USER_ID = '[PALCAR] SET USER ID';
export const TOGGLEBUTTON = '[PALCAR] TOGGLE BUTTON';
